language: c

os:
  - linux
  - osx

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - source asdf/asdf.sh
  # workaround: asdf plugin-test assumes master branch
  - cd $TRAVIS_BUILD_DIR && git checkout -b master || echo 'Already on master'

script:
  - asdf plugin-test docker-compose $TRAVIS_BUILD_DIR "docker-compose --version"
